/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element describes the destination of trips fulfilled by the given line.
    /// </summary>
    [DataContract]
        public partial class AdditionalInfoResponseAffectedLineDestination :  IEquatable<AdditionalInfoResponseAffectedLineDestination>, IValidatableObject
    {
        /// <summary>
        /// The type of the location the destination is.
        /// </summary>
        /// <value>The type of the location the destination is.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Poi for value: poi
            /// </summary>
            [EnumMember(Value = "poi")]
            Poi = 1,
            /// <summary>
            /// Enum Singlehouse for value: singlehouse
            /// </summary>
            [EnumMember(Value = "singlehouse")]
            Singlehouse = 2,
            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 3,
            /// <summary>
            /// Enum Platform for value: platform
            /// </summary>
            [EnumMember(Value = "platform")]
            Platform = 4,
            /// <summary>
            /// Enum Street for value: street
            /// </summary>
            [EnumMember(Value = "street")]
            Street = 5,
            /// <summary>
            /// Enum Locality for value: locality
            /// </summary>
            [EnumMember(Value = "locality")]
            Locality = 6,
            /// <summary>
            /// Enum Suburb for value: suburb
            /// </summary>
            [EnumMember(Value = "suburb")]
            Suburb = 7,
            /// <summary>
            /// Enum GisPoint for value: gisPoint
            /// </summary>
            [EnumMember(Value = "gisPoint")]
            GisPoint = 8,
            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown = 9        }
        /// <summary>
        /// The type of the location the destination is.
        /// </summary>
        /// <value>The type of the location the destination is.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalInfoResponseAffectedLineDestination" /> class.
        /// </summary>
        /// <param name="name">This is the name of the destination..</param>
        /// <param name="type">The type of the location the destination is..</param>
        public AdditionalInfoResponseAffectedLineDestination(string name = default, TypeEnum? type = default)
        {
            Name = name;
            Type = type;
        }
        
        /// <summary>
        /// This is the name of the destination.
        /// </summary>
        /// <value>This is the name of the destination.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdditionalInfoResponseAffectedLineDestination {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AdditionalInfoResponseAffectedLineDestination);
        }

        /// <summary>
        /// Returns true if AdditionalInfoResponseAffectedLineDestination instances are equal
        /// </summary>
        /// <param name="input">Instance of AdditionalInfoResponseAffectedLineDestination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalInfoResponseAffectedLineDestination input)
        {
            if (input == null)
                return false;

            return 
                (
                    Name == input.Name ||
                    Name != null &&
                    Name.Equals(input.Name)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
