/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This contains details about the lines and stops that are impacted by the described alert. 
    /// </summary>
    [DataContract]
        public partial class AdditionalInfoResponseMessageAffected :  IEquatable<AdditionalInfoResponseMessageAffected>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalInfoResponseMessageAffected" /> class.
        /// </summary>
        /// <param name="lines">This element contains a list of lines affected by this alert..</param>
        /// <param name="stops">This element contains a list of stops affected by this alert..</param>
        public AdditionalInfoResponseMessageAffected(List<AdditionalInfoResponseAffectedLine> lines = default, List<AdditionalInfoResponseAffectedStop> stops = default)
        {
            Lines = lines;
            Stops = stops;
        }
        
        /// <summary>
        /// This element contains a list of lines affected by this alert.
        /// </summary>
        /// <value>This element contains a list of lines affected by this alert.</value>
        [DataMember(Name="lines", EmitDefaultValue=false)]
        public List<AdditionalInfoResponseAffectedLine> Lines { get; set; }

        /// <summary>
        /// This element contains a list of stops affected by this alert.
        /// </summary>
        /// <value>This element contains a list of stops affected by this alert.</value>
        [DataMember(Name="stops", EmitDefaultValue=false)]
        public List<AdditionalInfoResponseAffectedStop> Stops { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdditionalInfoResponseMessageAffected {\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  Stops: ").Append(Stops).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AdditionalInfoResponseMessageAffected);
        }

        /// <summary>
        /// Returns true if AdditionalInfoResponseMessageAffected instances are equal
        /// </summary>
        /// <param name="input">Instance of AdditionalInfoResponseMessageAffected to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalInfoResponseMessageAffected input)
        {
            if (input == null)
                return false;

            return 
                (
                    Lines == input.Lines ||
                    Lines != null &&
                    input.Lines != null &&
                    Lines.SequenceEqual(input.Lines)
                ) && 
                (
                    Stops == input.Stops ||
                    Stops != null &&
                    input.Stops != null &&
                    Stops.SequenceEqual(input.Stops)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Lines != null)
                    hashCode = hashCode * 59 + Lines.GetHashCode();
                if (Stops != null)
                    hashCode = hashCode * 59 + Stops.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
