/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Contains each of the returned service alerts. 
    /// </summary>
    [DataContract]
        public partial class AdditionalInfoResponseInfos :  IEquatable<AdditionalInfoResponseInfos>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalInfoResponseInfos" /> class.
        /// </summary>
        /// <param name="affected">affected.</param>
        /// <param name="current">This specifies the list of current service alerts based on the specified filters..</param>
        /// <param name="historic">This specifies the list of previous service alerts based on the specified filters..</param>
        public AdditionalInfoResponseInfos(AdditionalInfoResponseInfosAffected affected = default, List<AdditionalInfoResponseMessage> current = default, List<AdditionalInfoResponseMessage> historic = default)
        {
            Affected = affected;
            Current = current;
            Historic = historic;
        }
        
        /// <summary>
        /// Gets or Sets Affected
        /// </summary>
        [DataMember(Name="affected", EmitDefaultValue=false)]
        public AdditionalInfoResponseInfosAffected Affected { get; set; }

        /// <summary>
        /// This specifies the list of current service alerts based on the specified filters.
        /// </summary>
        /// <value>This specifies the list of current service alerts based on the specified filters.</value>
        [DataMember(Name="current", EmitDefaultValue=false)]
        public List<AdditionalInfoResponseMessage> Current { get; set; }

        /// <summary>
        /// This specifies the list of previous service alerts based on the specified filters.
        /// </summary>
        /// <value>This specifies the list of previous service alerts based on the specified filters.</value>
        [DataMember(Name="historic", EmitDefaultValue=false)]
        public List<AdditionalInfoResponseMessage> Historic { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdditionalInfoResponseInfos {\n");
            sb.Append("  Affected: ").Append(Affected).Append("\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Historic: ").Append(Historic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AdditionalInfoResponseInfos);
        }

        /// <summary>
        /// Returns true if AdditionalInfoResponseInfos instances are equal
        /// </summary>
        /// <param name="input">Instance of AdditionalInfoResponseInfos to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalInfoResponseInfos input)
        {
            if (input == null)
                return false;

            return 
                (
                    Affected == input.Affected ||
                    Affected != null &&
                    Affected.Equals(input.Affected)
                ) && 
                (
                    Current == input.Current ||
                    Current != null &&
                    input.Current != null &&
                    Current.SequenceEqual(input.Current)
                ) && 
                (
                    Historic == input.Historic ||
                    Historic != null &&
                    input.Historic != null &&
                    Historic.SequenceEqual(input.Historic)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Affected != null)
                    hashCode = hashCode * 59 + Affected.GetHashCode();
                if (Current != null)
                    hashCode = hashCode * 59 + Current.GetHashCode();
                if (Historic != null)
                    hashCode = hashCode * 59 + Historic.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
