/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element describes a single service alert.
    /// </summary>
    [DataContract]
        public partial class AdditionalInfoResponseMessage :  IEquatable<AdditionalInfoResponseMessage>, IValidatableObject
    {
        /// <summary>
        /// This value indicates how important the service alert is. A value of &#x60;high&#x60; or &#x60;veryHigh&#x60; likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while &#x60;low&#x60; or &#x60;veryLow&#x60; might be more of an informational message. 
        /// </summary>
        /// <value>This value indicates how important the service alert is. A value of &#x60;high&#x60; or &#x60;veryHigh&#x60; likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while &#x60;low&#x60; or &#x60;veryLow&#x60; might be more of an informational message. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum PriorityEnum
        {
            /// <summary>
            /// Enum VeryLow for value: veryLow
            /// </summary>
            [EnumMember(Value = "veryLow")]
            VeryLow = 1,
            /// <summary>
            /// Enum Low for value: low
            /// </summary>
            [EnumMember(Value = "low")]
            Low = 2,
            /// <summary>
            /// Enum Normal for value: normal
            /// </summary>
            [EnumMember(Value = "normal")]
            Normal = 3,
            /// <summary>
            /// Enum High for value: high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 4,
            /// <summary>
            /// Enum VeryHigh for value: veryHigh
            /// </summary>
            [EnumMember(Value = "veryHigh")]
            VeryHigh = 5        }
        /// <summary>
        /// This value indicates how important the service alert is. A value of &#x60;high&#x60; or &#x60;veryHigh&#x60; likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while &#x60;low&#x60; or &#x60;veryLow&#x60; might be more of an informational message. 
        /// </summary>
        /// <value>This value indicates how important the service alert is. A value of &#x60;high&#x60; or &#x60;veryHigh&#x60; likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while &#x60;low&#x60; or &#x60;veryLow&#x60; might be more of an informational message. </value>
        [DataMember(Name="priority", EmitDefaultValue=false)]
        public PriorityEnum? Priority { get; set; }
        /// <summary>
        /// This indicates the category of the service alert. For example, if this value is &#x60;stopInfo&#x60;, then the alert is related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at the affected stop.  * &#x60;routeInfo&#x60;: The alert is related to a specific route * &#x60;stopInfo&#x60;: The alert is related to a specific stop * &#x60;stopBlocking&#x60;: This alert is related to a stop closure * &#x60;lineInfo&#x60;: The alert is related to a specific journey * &#x60;bannerInfo&#x60;: The alert of high importance and potentially has a network-wide impact. 
        /// </summary>
        /// <value>This indicates the category of the service alert. For example, if this value is &#x60;stopInfo&#x60;, then the alert is related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at the affected stop.  * &#x60;routeInfo&#x60;: The alert is related to a specific route * &#x60;stopInfo&#x60;: The alert is related to a specific stop * &#x60;stopBlocking&#x60;: This alert is related to a stop closure * &#x60;lineInfo&#x60;: The alert is related to a specific journey * &#x60;bannerInfo&#x60;: The alert of high importance and potentially has a network-wide impact. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum RouteInfo for value: routeInfo
            /// </summary>
            [EnumMember(Value = "routeInfo")]
            RouteInfo = 1,
            /// <summary>
            /// Enum StopInfo for value: stopInfo
            /// </summary>
            [EnumMember(Value = "stopInfo")]
            StopInfo = 2,
            /// <summary>
            /// Enum LineInfo for value: lineInfo
            /// </summary>
            [EnumMember(Value = "lineInfo")]
            LineInfo = 3,
            /// <summary>
            /// Enum BannerInfo for value: bannerInfo
            /// </summary>
            [EnumMember(Value = "bannerInfo")]
            BannerInfo = 4,
            /// <summary>
            /// Enum StopBlocking for value: stopBlocking
            /// </summary>
            [EnumMember(Value = "stopBlocking")]
            StopBlocking = 5        }
        /// <summary>
        /// This indicates the category of the service alert. For example, if this value is &#x60;stopInfo&#x60;, then the alert is related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at the affected stop.  * &#x60;routeInfo&#x60;: The alert is related to a specific route * &#x60;stopInfo&#x60;: The alert is related to a specific stop * &#x60;stopBlocking&#x60;: This alert is related to a stop closure * &#x60;lineInfo&#x60;: The alert is related to a specific journey * &#x60;bannerInfo&#x60;: The alert of high importance and potentially has a network-wide impact. 
        /// </summary>
        /// <value>This indicates the category of the service alert. For example, if this value is &#x60;stopInfo&#x60;, then the alert is related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at the affected stop.  * &#x60;routeInfo&#x60;: The alert is related to a specific route * &#x60;stopInfo&#x60;: The alert is related to a specific stop * &#x60;stopBlocking&#x60;: This alert is related to a stop closure * &#x60;lineInfo&#x60;: The alert is related to a specific journey * &#x60;bannerInfo&#x60;: The alert of high importance and potentially has a network-wide impact. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalInfoResponseMessage" /> class.
        /// </summary>
        /// <param name="affected">affected.</param>
        /// <param name="content">This is the descriptive alert content. It may contain HTML tags and/or HTML entities. .</param>
        /// <param name="id">This is a unique identifier for this particular service alert. .</param>
        /// <param name="priority">This value indicates how important the service alert is. A value of &#x60;high&#x60; or &#x60;veryHigh&#x60; likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while &#x60;low&#x60; or &#x60;veryLow&#x60; might be more of an informational message. .</param>
        /// <param name="properties">properties.</param>
        /// <param name="subtitle">This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities. .</param>
        /// <param name="timestamps">timestamps.</param>
        /// <param name="type">This indicates the category of the service alert. For example, if this value is &#x60;stopInfo&#x60;, then the alert is related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at the affected stop.  * &#x60;routeInfo&#x60;: The alert is related to a specific route * &#x60;stopInfo&#x60;: The alert is related to a specific stop * &#x60;stopBlocking&#x60;: This alert is related to a stop closure * &#x60;lineInfo&#x60;: The alert is related to a specific journey * &#x60;bannerInfo&#x60;: The alert of high importance and potentially has a network-wide impact. .</param>
        /// <param name="url">This field contains a URL that contains additional information about the alert..</param>
        /// <param name="urlText">This field contains a title that can be used when displaying the &#x60;infoLinkURL&#x60; URL..</param>
        /// <param name="version">This number indicates the version of this alert. Initially when it is created it has version &#x60;1&#x60;, but if it is then updated it will have a new &#x60;lastModification&#x60; value and the version will now be &#x60;2&#x60;. .</param>
        public AdditionalInfoResponseMessage(AdditionalInfoResponseMessageAffected affected = default, string content = default, string id = default, PriorityEnum? priority = default, AdditionalInfoResponseMessageProperties properties = default, string subtitle = default, AdditionalInfoResponseTimestamps timestamps = default, TypeEnum? type = default, string url = default, string urlText = default, int? version = default)
        {
            Affected = affected;
            Content = content;
            Id = id;
            Priority = priority;
            Properties = properties;
            Subtitle = subtitle;
            Timestamps = timestamps;
            Type = type;
            Url = url;
            UrlText = urlText;
            Version = version;
        }
        
        /// <summary>
        /// Gets or Sets Affected
        /// </summary>
        [DataMember(Name="affected", EmitDefaultValue=false)]
        public AdditionalInfoResponseMessageAffected Affected { get; set; }

        /// <summary>
        /// This is the descriptive alert content. It may contain HTML tags and/or HTML entities. 
        /// </summary>
        /// <value>This is the descriptive alert content. It may contain HTML tags and/or HTML entities. </value>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public string Content { get; set; }

        /// <summary>
        /// This is a unique identifier for this particular service alert. 
        /// </summary>
        /// <value>This is a unique identifier for this particular service alert. </value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }


        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name="properties", EmitDefaultValue=false)]
        public AdditionalInfoResponseMessageProperties Properties { get; set; }

        /// <summary>
        /// This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities. 
        /// </summary>
        /// <value>This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities. </value>
        [DataMember(Name="subtitle", EmitDefaultValue=false)]
        public string Subtitle { get; set; }

        /// <summary>
        /// Gets or Sets Timestamps
        /// </summary>
        [DataMember(Name="timestamps", EmitDefaultValue=false)]
        public AdditionalInfoResponseTimestamps Timestamps { get; set; }


        /// <summary>
        /// This field contains a URL that contains additional information about the alert.
        /// </summary>
        /// <value>This field contains a URL that contains additional information about the alert.</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// This field contains a title that can be used when displaying the &#x60;infoLinkURL&#x60; URL.
        /// </summary>
        /// <value>This field contains a title that can be used when displaying the &#x60;infoLinkURL&#x60; URL.</value>
        [DataMember(Name="urlText", EmitDefaultValue=false)]
        public string UrlText { get; set; }

        /// <summary>
        /// This number indicates the version of this alert. Initially when it is created it has version &#x60;1&#x60;, but if it is then updated it will have a new &#x60;lastModification&#x60; value and the version will now be &#x60;2&#x60;. 
        /// </summary>
        /// <value>This number indicates the version of this alert. Initially when it is created it has version &#x60;1&#x60;, but if it is then updated it will have a new &#x60;lastModification&#x60; value and the version will now be &#x60;2&#x60;. </value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public int? Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdditionalInfoResponseMessage {\n");
            sb.Append("  Affected: ").Append(Affected).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Subtitle: ").Append(Subtitle).Append("\n");
            sb.Append("  Timestamps: ").Append(Timestamps).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  UrlText: ").Append(UrlText).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AdditionalInfoResponseMessage);
        }

        /// <summary>
        /// Returns true if AdditionalInfoResponseMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of AdditionalInfoResponseMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalInfoResponseMessage input)
        {
            if (input == null)
                return false;

            return 
                (
                    Affected == input.Affected ||
                    Affected != null &&
                    Affected.Equals(input.Affected)
                ) && 
                (
                    Content == input.Content ||
                    Content != null &&
                    Content.Equals(input.Content)
                ) && 
                (
                    Id == input.Id ||
                    Id != null &&
                    Id.Equals(input.Id)
                ) && 
                (
                    Priority == input.Priority ||
                    Priority != null &&
                    Priority.Equals(input.Priority)
                ) && 
                (
                    Properties == input.Properties ||
                    Properties != null &&
                    Properties.Equals(input.Properties)
                ) && 
                (
                    Subtitle == input.Subtitle ||
                    Subtitle != null &&
                    Subtitle.Equals(input.Subtitle)
                ) && 
                (
                    Timestamps == input.Timestamps ||
                    Timestamps != null &&
                    Timestamps.Equals(input.Timestamps)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                ) && 
                (
                    Url == input.Url ||
                    Url != null &&
                    Url.Equals(input.Url)
                ) && 
                (
                    UrlText == input.UrlText ||
                    UrlText != null &&
                    UrlText.Equals(input.UrlText)
                ) && 
                (
                    Version == input.Version ||
                    Version != null &&
                    Version.Equals(input.Version)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Affected != null)
                    hashCode = hashCode * 59 + Affected.GetHashCode();
                if (Content != null)
                    hashCode = hashCode * 59 + Content.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Priority != null)
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                if (Properties != null)
                    hashCode = hashCode * 59 + Properties.GetHashCode();
                if (Subtitle != null)
                    hashCode = hashCode * 59 + Subtitle.GetHashCode();
                if (Timestamps != null)
                    hashCode = hashCode * 59 + Timestamps.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                if (UrlText != null)
                    hashCode = hashCode * 59 + UrlText.GetHashCode();
                if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
