/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element contains information about an error that may have occurred when handling an API request. 
    /// </summary>
    [DataContract]
        public partial class ApiErrorResponse :  IEquatable<ApiErrorResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiErrorResponse" /> class.
        /// </summary>
        /// <param name="message">Describes the error that went wrong.</param>
        /// <param name="versions">versions.</param>
        public ApiErrorResponse(string message = default, ApiErrorResponseVersions versions = default)
        {
            Message = message;
            Versions = versions;
        }
        
        /// <summary>
        /// Describes the error that went wrong
        /// </summary>
        /// <value>Describes the error that went wrong</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Versions
        /// </summary>
        [DataMember(Name="versions", EmitDefaultValue=false)]
        public ApiErrorResponseVersions Versions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiErrorResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Versions: ").Append(Versions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ApiErrorResponse);
        }

        /// <summary>
        /// Returns true if ApiErrorResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiErrorResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiErrorResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    Message == input.Message ||
                    Message != null &&
                    Message.Equals(input.Message)
                ) && 
                (
                    Versions == input.Versions ||
                    Versions != null &&
                    Versions.Equals(input.Versions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                if (Versions != null)
                    hashCode = hashCode * 59 + Versions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
