/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This data contains additional information about each location, mainly related to how it can be categorised or displayed on a map. 
    /// </summary>
    [DataContract]
        public partial class CoordRequestResponseLocationProperties :  IEquatable<CoordRequestResponseLocationProperties>, IValidatableObject
    {
        /// <summary>
        /// This value typically either empty or &#x60;POINT&#x60;.
        /// </summary>
        /// <value>This value typically either empty or &#x60;POINT&#x60;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum GISDRAWCLASSTYPEEnum
        {
            /// <summary>
            /// Enum POINT for value: POINT
            /// </summary>
            [EnumMember(Value = "POINT")]
            POINT = 1        }
        /// <summary>
        /// This value typically either empty or &#x60;POINT&#x60;.
        /// </summary>
        /// <value>This value typically either empty or &#x60;POINT&#x60;.</value>
        [DataMember(Name="GIS_DRAW_CLASS_TYPE", EmitDefaultValue=false)]
        public GISDRAWCLASSTYPEEnum? GIS_DRAW_CLASS_TYPE { get; set; }
        /// <summary>
        /// This value typically either empty or &#x60;POINT&#x60;.
        /// </summary>
        /// <value>This value typically either empty or &#x60;POINT&#x60;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum POIDRAWCLASSTYPEEnum
        {
            /// <summary>
            /// Enum POINT for value: POINT
            /// </summary>
            [EnumMember(Value = "POINT")]
            POINT = 1        }
        /// <summary>
        /// This value typically either empty or &#x60;POINT&#x60;.
        /// </summary>
        /// <value>This value typically either empty or &#x60;POINT&#x60;.</value>
        [DataMember(Name="POI_DRAW_CLASS_TYPE", EmitDefaultValue=false)]
        public POIDRAWCLASSTYPEEnum? POI_DRAW_CLASS_TYPE { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CoordRequestResponseLocationProperties" /> class.
        /// </summary>
        /// <param name="gISDRAWCLASS">This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;CityL&#x60; * &#x60;CityM&#x60; * &#x60;CityS&#x60; * &#x60;CityXL&#x60; * &#x60;CityXS&#x60; * &#x60;Generic7&#x60; * &#x60;Generic8&#x60; * &#x60;Generic9&#x60; * &#x60;Generic20&#x60; * &#x60;PoiAirportPublic&#x60; * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHistoric&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; .</param>
        /// <param name="gISDRAWCLASSTYPE">This value typically either empty or &#x60;POINT&#x60;..</param>
        /// <param name="gISNIVEAU">This data is not used at this time..</param>
        /// <param name="pOIDRAWCLASS">This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; .</param>
        /// <param name="pOIDRAWCLASSTYPE">This value typically either empty or &#x60;POINT&#x60;..</param>
        /// <param name="pOIHIERARCHY0">This field contains a human-readable description of the category to which this location belongs. See the description for &#x60;POI_HIERARCHY_KEY&#x60; for example values that correspond to the given keys. .</param>
        /// <param name="pOIHIERARCHYKEY">This field contains a constant value for the category to which this category belongs.  * &#x60;A&#x60;: Accommodation * &#x60;B&#x60;: Caravan and Camping * &#x60;C&#x60;: Cemetary * &#x60;D&#x60;: Education * &#x60;E&#x60;: Emergency or Defence * &#x60;F&#x60;: Entertainment * &#x60;G&#x60;: Gardens or Parklands * &#x60;H&#x60;: Golf Clubs * &#x60;I&#x60;: Historical or Religious * &#x60;K&#x60;: Local Government * &#x60;L&#x60;: Medical and Care * &#x60;O&#x60;: Sporting or Recreation * &#x60;Q&#x60;: Tourist Attraction * &#x60;R&#x60;: Transport * &#x60;S&#x60;: Utilities and Facilities * &#x60;T&#x60;: Others .</param>
        /// <param name="distance">This is the distance in metres to this location from the search location..</param>
        public CoordRequestResponseLocationProperties(string gISDRAWCLASS = default, GISDRAWCLASSTYPEEnum? gISDRAWCLASSTYPE = default, string gISNIVEAU = default, string pOIDRAWCLASS = default, POIDRAWCLASSTYPEEnum? pOIDRAWCLASSTYPE = default, string pOIHIERARCHY0 = default, string pOIHIERARCHYKEY = default, string distance = default)
        {
            GIS_DRAW_CLASS = gISDRAWCLASS;
            GIS_DRAW_CLASS_TYPE = gISDRAWCLASSTYPE;
            GIS_NIVEAU = gISNIVEAU;
            POI_DRAW_CLASS = pOIDRAWCLASS;
            POI_DRAW_CLASS_TYPE = pOIDRAWCLASSTYPE;
            POIHIERARCHY0 = pOIHIERARCHY0;
            POI_HIERARCHY_KEY = pOIHIERARCHYKEY;
            Distance = distance;
        }
        
        /// <summary>
        /// This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;CityL&#x60; * &#x60;CityM&#x60; * &#x60;CityS&#x60; * &#x60;CityXL&#x60; * &#x60;CityXS&#x60; * &#x60;Generic7&#x60; * &#x60;Generic8&#x60; * &#x60;Generic9&#x60; * &#x60;Generic20&#x60; * &#x60;PoiAirportPublic&#x60; * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHistoric&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; 
        /// </summary>
        /// <value>This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;CityL&#x60; * &#x60;CityM&#x60; * &#x60;CityS&#x60; * &#x60;CityXL&#x60; * &#x60;CityXS&#x60; * &#x60;Generic7&#x60; * &#x60;Generic8&#x60; * &#x60;Generic9&#x60; * &#x60;Generic20&#x60; * &#x60;PoiAirportPublic&#x60; * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHistoric&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; </value>
        [DataMember(Name="GIS_DRAW_CLASS", EmitDefaultValue=false)]
        public string GIS_DRAW_CLASS { get; set; }


        /// <summary>
        /// This data is not used at this time.
        /// </summary>
        /// <value>This data is not used at this time.</value>
        [DataMember(Name="GIS_NIVEAU", EmitDefaultValue=false)]
        public string GIS_NIVEAU { get; set; }

        /// <summary>
        /// This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; 
        /// </summary>
        /// <value>This value indicates how the given point can be represented on a map. For example, if you have different icons for different categories, use this to determine which icon to use.  * &#x60;PoiCemetry&#x60; * &#x60;PoiCulture&#x60; * &#x60;PoiGastro&#x60; * &#x60;PoiGeneral&#x60; * &#x60;PoiGovernment&#x60; * &#x60;PoiHotel&#x60; * &#x60;PoiMedicine&#x60; * &#x60;PoiOthers&#x60; * &#x60;PoiPark&#x60; * &#x60;PoiParking&#x60; * &#x60;PoiPublicBuilding&#x60; * &#x60;PoiReligion&#x60; * &#x60;PoiSchool&#x60; * &#x60;PoiSport&#x60; * &#x60;PoiSwimming&#x60; * &#x60;PoiTrafficSpecial&#x60; </value>
        [DataMember(Name="POI_DRAW_CLASS", EmitDefaultValue=false)]
        public string POI_DRAW_CLASS { get; set; }


        /// <summary>
        /// This field contains a human-readable description of the category to which this location belongs. See the description for &#x60;POI_HIERARCHY_KEY&#x60; for example values that correspond to the given keys. 
        /// </summary>
        /// <value>This field contains a human-readable description of the category to which this location belongs. See the description for &#x60;POI_HIERARCHY_KEY&#x60; for example values that correspond to the given keys. </value>
        [DataMember(Name="POI_HIERARCHY_0", EmitDefaultValue=false)]
        public string POIHIERARCHY0 { get; set; }

        /// <summary>
        /// This field contains a constant value for the category to which this category belongs.  * &#x60;A&#x60;: Accommodation * &#x60;B&#x60;: Caravan and Camping * &#x60;C&#x60;: Cemetary * &#x60;D&#x60;: Education * &#x60;E&#x60;: Emergency or Defence * &#x60;F&#x60;: Entertainment * &#x60;G&#x60;: Gardens or Parklands * &#x60;H&#x60;: Golf Clubs * &#x60;I&#x60;: Historical or Religious * &#x60;K&#x60;: Local Government * &#x60;L&#x60;: Medical and Care * &#x60;O&#x60;: Sporting or Recreation * &#x60;Q&#x60;: Tourist Attraction * &#x60;R&#x60;: Transport * &#x60;S&#x60;: Utilities and Facilities * &#x60;T&#x60;: Others 
        /// </summary>
        /// <value>This field contains a constant value for the category to which this category belongs.  * &#x60;A&#x60;: Accommodation * &#x60;B&#x60;: Caravan and Camping * &#x60;C&#x60;: Cemetary * &#x60;D&#x60;: Education * &#x60;E&#x60;: Emergency or Defence * &#x60;F&#x60;: Entertainment * &#x60;G&#x60;: Gardens or Parklands * &#x60;H&#x60;: Golf Clubs * &#x60;I&#x60;: Historical or Religious * &#x60;K&#x60;: Local Government * &#x60;L&#x60;: Medical and Care * &#x60;O&#x60;: Sporting or Recreation * &#x60;Q&#x60;: Tourist Attraction * &#x60;R&#x60;: Transport * &#x60;S&#x60;: Utilities and Facilities * &#x60;T&#x60;: Others </value>
        [DataMember(Name="POI_HIERARCHY_KEY", EmitDefaultValue=false)]
        public string POI_HIERARCHY_KEY { get; set; }

        /// <summary>
        /// This is the distance in metres to this location from the search location.
        /// </summary>
        /// <value>This is the distance in metres to this location from the search location.</value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public string Distance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CoordRequestResponseLocationProperties {\n");
            sb.Append("  GIS_DRAW_CLASS: ").Append(GIS_DRAW_CLASS).Append("\n");
            sb.Append("  GIS_DRAW_CLASS_TYPE: ").Append(GIS_DRAW_CLASS_TYPE).Append("\n");
            sb.Append("  GIS_NIVEAU: ").Append(GIS_NIVEAU).Append("\n");
            sb.Append("  POI_DRAW_CLASS: ").Append(POI_DRAW_CLASS).Append("\n");
            sb.Append("  POI_DRAW_CLASS_TYPE: ").Append(POI_DRAW_CLASS_TYPE).Append("\n");
            sb.Append("  POIHIERARCHY0: ").Append(POIHIERARCHY0).Append("\n");
            sb.Append("  POI_HIERARCHY_KEY: ").Append(POI_HIERARCHY_KEY).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CoordRequestResponseLocationProperties);
        }

        /// <summary>
        /// Returns true if CoordRequestResponseLocationProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of CoordRequestResponseLocationProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CoordRequestResponseLocationProperties input)
        {
            if (input == null)
                return false;

            return 
                (
                    GIS_DRAW_CLASS == input.GIS_DRAW_CLASS ||
                    GIS_DRAW_CLASS != null &&
                    GIS_DRAW_CLASS.Equals(input.GIS_DRAW_CLASS)
                ) && 
                (
                    GIS_DRAW_CLASS_TYPE == input.GIS_DRAW_CLASS_TYPE ||
                    GIS_DRAW_CLASS_TYPE != null &&
                    GIS_DRAW_CLASS_TYPE.Equals(input.GIS_DRAW_CLASS_TYPE)
                ) && 
                (
                    GIS_NIVEAU == input.GIS_NIVEAU ||
                    GIS_NIVEAU != null &&
                    GIS_NIVEAU.Equals(input.GIS_NIVEAU)
                ) && 
                (
                    POI_DRAW_CLASS == input.POI_DRAW_CLASS ||
                    POI_DRAW_CLASS != null &&
                    POI_DRAW_CLASS.Equals(input.POI_DRAW_CLASS)
                ) && 
                (
                    POI_DRAW_CLASS_TYPE == input.POI_DRAW_CLASS_TYPE ||
                    POI_DRAW_CLASS_TYPE != null &&
                    POI_DRAW_CLASS_TYPE.Equals(input.POI_DRAW_CLASS_TYPE)
                ) && 
                (
                    POIHIERARCHY0 == input.POIHIERARCHY0 ||
                    POIHIERARCHY0 != null &&
                    POIHIERARCHY0.Equals(input.POIHIERARCHY0)
                ) && 
                (
                    POI_HIERARCHY_KEY == input.POI_HIERARCHY_KEY ||
                    POI_HIERARCHY_KEY != null &&
                    POI_HIERARCHY_KEY.Equals(input.POI_HIERARCHY_KEY)
                ) && 
                (
                    Distance == input.Distance ||
                    Distance != null &&
                    Distance.Equals(input.Distance)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (GIS_DRAW_CLASS != null)
                    hashCode = hashCode * 59 + GIS_DRAW_CLASS.GetHashCode();
                if (GIS_DRAW_CLASS_TYPE != null)
                    hashCode = hashCode * 59 + GIS_DRAW_CLASS_TYPE.GetHashCode();
                if (GIS_NIVEAU != null)
                    hashCode = hashCode * 59 + GIS_NIVEAU.GetHashCode();
                if (POI_DRAW_CLASS != null)
                    hashCode = hashCode * 59 + POI_DRAW_CLASS.GetHashCode();
                if (POI_DRAW_CLASS_TYPE != null)
                    hashCode = hashCode * 59 + POI_DRAW_CLASS_TYPE.GetHashCode();
                if (POIHIERARCHY0 != null)
                    hashCode = hashCode * 59 + POIHIERARCHY0.GetHashCode();
                if (POI_HIERARCHY_KEY != null)
                    hashCode = hashCode * 59 + POI_HIERARCHY_KEY.GetHashCode();
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
