/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This is the response data returned when performing an &#x60;coord&#x60; request. 
    /// </summary>
    [DataContract]
        public partial class CoordRequestResponse :  IEquatable<CoordRequestResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CoordRequestResponse" /> class.
        /// </summary>
        /// <param name="error">error.</param>
        /// <param name="locations">This contains a list of all of the stops, reload points and places of interest found based on the given request. .</param>
        /// <param name="version">The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the &#x60;version&#x60; request parameter. .</param>
        public CoordRequestResponse(ApiErrorResponse error = default, List<CoordRequestResponseLocation> locations = default, string version = default)
        {
            Error = error;
            Locations = locations;
            Version = version;
        }
        
        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public ApiErrorResponse Error { get; set; }

        /// <summary>
        /// This contains a list of all of the stops, reload points and places of interest found based on the given request. 
        /// </summary>
        /// <value>This contains a list of all of the stops, reload points and places of interest found based on the given request. </value>
        [DataMember(Name="locations", EmitDefaultValue=false)]
        public List<CoordRequestResponseLocation> Locations { get; set; }

        /// <summary>
        /// The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the &#x60;version&#x60; request parameter. 
        /// </summary>
        /// <value>The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the &#x60;version&#x60; request parameter. </value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CoordRequestResponse {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CoordRequestResponse);
        }

        /// <summary>
        /// Returns true if CoordRequestResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CoordRequestResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CoordRequestResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    Error == input.Error ||
                    Error != null &&
                    Error.Equals(input.Error)
                ) && 
                (
                    Locations == input.Locations ||
                    Locations != null &&
                    input.Locations != null &&
                    Locations.SequenceEqual(input.Locations)
                ) && 
                (
                    Version == input.Version ||
                    Version != null &&
                    Version.Equals(input.Version)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Error != null)
                    hashCode = hashCode * 59 + Error.GetHashCode();
                if (Locations != null)
                    hashCode = hashCode * 59 + Locations.GetHashCode();
                if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
