/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Corresponds to a single departure or arrival for the given stop. 
    /// </summary>
    [DataContract]
        public partial class DepartureMonitorResponseStopEvent :  IEquatable<DepartureMonitorResponseStopEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DepartureMonitorResponseStopEvent" /> class.
        /// </summary>
        /// <param name="departureTimePlanned">A timestamp in &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60; format.</param>
        /// <param name="infos">Contains a number of service alert messages relating to this stop event. Information returned here is also available using the &#x60;add_info&#x60; API endpoint. .</param>
        /// <param name="location">location.</param>
        /// <param name="transportation">transportation.</param>
        public DepartureMonitorResponseStopEvent(string departureTimePlanned = default, List<TripRequestResponseJourneyLegStopInfo> infos = default, StopFinderLocation location = default, TripTransportation transportation = default)
        {
            DepartureTimePlanned = departureTimePlanned;
            Infos = infos;
            Location = location;
            Transportation = transportation;
        }
        
        /// <summary>
        /// A timestamp in &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60; format
        /// </summary>
        /// <value>A timestamp in &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60; format</value>
        [DataMember(Name="departureTimePlanned", EmitDefaultValue=false)]
        public string DepartureTimePlanned { get; set; }

        /// <summary>
        /// Contains a number of service alert messages relating to this stop event. Information returned here is also available using the &#x60;add_info&#x60; API endpoint. 
        /// </summary>
        /// <value>Contains a number of service alert messages relating to this stop event. Information returned here is also available using the &#x60;add_info&#x60; API endpoint. </value>
        [DataMember(Name="infos", EmitDefaultValue=false)]
        public List<TripRequestResponseJourneyLegStopInfo> Infos { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public StopFinderLocation Location { get; set; }

        /// <summary>
        /// Gets or Sets Transportation
        /// </summary>
        [DataMember(Name="transportation", EmitDefaultValue=false)]
        public TripTransportation Transportation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DepartureMonitorResponseStopEvent {\n");
            sb.Append("  DepartureTimePlanned: ").Append(DepartureTimePlanned).Append("\n");
            sb.Append("  Infos: ").Append(Infos).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Transportation: ").Append(Transportation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as DepartureMonitorResponseStopEvent);
        }

        /// <summary>
        /// Returns true if DepartureMonitorResponseStopEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of DepartureMonitorResponseStopEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DepartureMonitorResponseStopEvent input)
        {
            if (input == null)
                return false;

            return 
                (
                    DepartureTimePlanned == input.DepartureTimePlanned ||
                    DepartureTimePlanned != null &&
                    DepartureTimePlanned.Equals(input.DepartureTimePlanned)
                ) && 
                (
                    Infos == input.Infos ||
                    Infos != null &&
                    input.Infos != null &&
                    Infos.SequenceEqual(input.Infos)
                ) && 
                (
                    Location == input.Location ||
                    Location != null &&
                    Location.Equals(input.Location)
                ) && 
                (
                    Transportation == input.Transportation ||
                    Transportation != null &&
                    Transportation.Equals(input.Transportation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (DepartureTimePlanned != null)
                    hashCode = hashCode * 59 + DepartureTimePlanned.GetHashCode();
                if (Infos != null)
                    hashCode = hashCode * 59 + Infos.GetHashCode();
                if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                if (Transportation != null)
                    hashCode = hashCode * 59 + Transportation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
