/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Describes a parent location. Locations are hierarchical, mean a location has a parent, and a location may have any number of child locations. A parent location is often included with locations, which can help traverse the location tree. 
    /// </summary>
    [DataContract]
        public partial class ParentLocation :  IEquatable<ParentLocation>, IValidatableObject
    {
        /// <summary>
        /// This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. 
        /// </summary>
        /// <value>This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Poi for value: poi
            /// </summary>
            [EnumMember(Value = "poi")]
            Poi = 1,
            /// <summary>
            /// Enum Singlehouse for value: singlehouse
            /// </summary>
            [EnumMember(Value = "singlehouse")]
            Singlehouse = 2,
            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 3,
            /// <summary>
            /// Enum Platform for value: platform
            /// </summary>
            [EnumMember(Value = "platform")]
            Platform = 4,
            /// <summary>
            /// Enum Street for value: street
            /// </summary>
            [EnumMember(Value = "street")]
            Street = 5,
            /// <summary>
            /// Enum Locality for value: locality
            /// </summary>
            [EnumMember(Value = "locality")]
            Locality = 6,
            /// <summary>
            /// Enum Suburb for value: suburb
            /// </summary>
            [EnumMember(Value = "suburb")]
            Suburb = 7,
            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown = 8        }
        /// <summary>
        /// This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. 
        /// </summary>
        /// <value>This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParentLocation" /> class.
        /// </summary>
        /// <param name="disassembledName">This is the short version of the location name, which does not include the suburb or other information. .</param>
        /// <param name="id">This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. .</param>
        /// <param name="name">This is the long version of the location name, which may include the suburb or other information. .</param>
        /// <param name="parent">parent.</param>
        /// <param name="type">This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. .</param>
        public ParentLocation(string disassembledName = default, string id = default, string name = default, ParentLocation parent = default, TypeEnum? type = default)
        {
            DisassembledName = disassembledName;
            Id = id;
            Name = name;
            Parent = parent;
            Type = type;
        }
        
        /// <summary>
        /// This is the short version of the location name, which does not include the suburb or other information. 
        /// </summary>
        /// <value>This is the short version of the location name, which does not include the suburb or other information. </value>
        [DataMember(Name="disassembledName", EmitDefaultValue=false)]
        public string DisassembledName { get; set; }

        /// <summary>
        /// This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. 
        /// </summary>
        /// <value>This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. </value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// This is the long version of the location name, which may include the suburb or other information. 
        /// </summary>
        /// <value>This is the long version of the location name, which may include the suburb or other information. </value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Parent
        /// </summary>
        [DataMember(Name="parent", EmitDefaultValue=false)]
        public ParentLocation Parent { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParentLocation {\n");
            sb.Append("  DisassembledName: ").Append(DisassembledName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ParentLocation);
        }

        /// <summary>
        /// Returns true if ParentLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of ParentLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParentLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    DisassembledName == input.DisassembledName ||
                    DisassembledName != null &&
                    DisassembledName.Equals(input.DisassembledName)
                ) && 
                (
                    Id == input.Id ||
                    Id != null &&
                    Id.Equals(input.Id)
                ) && 
                (
                    Name == input.Name ||
                    Name != null &&
                    Name.Equals(input.Name)
                ) && 
                (
                    Parent == input.Parent ||
                    Parent != null &&
                    Parent.Equals(input.Parent)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (DisassembledName != null)
                    hashCode = hashCode * 59 + DisassembledName.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Parent != null)
                    hashCode = hashCode * 59 + Parent.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
