/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element describes a single location that is returned in an &#x60;stop_finder&#x60; request.
    /// </summary>
    [DataContract]
        public partial class StopFinderLocation :  IEquatable<StopFinderLocation>, IValidatableObject
    {
        /// <summary>
        /// This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. 
        /// </summary>
        /// <value>This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Poi for value: poi
            /// </summary>
            [EnumMember(Value = "poi")]
            Poi = 1,
            /// <summary>
            /// Enum Singlehouse for value: singlehouse
            /// </summary>
            [EnumMember(Value = "singlehouse")]
            Singlehouse = 2,
            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 3,
            /// <summary>
            /// Enum Platform for value: platform
            /// </summary>
            [EnumMember(Value = "platform")]
            Platform = 4,
            /// <summary>
            /// Enum Street for value: street
            /// </summary>
            [EnumMember(Value = "street")]
            Street = 5,
            /// <summary>
            /// Enum Locality for value: locality
            /// </summary>
            [EnumMember(Value = "locality")]
            Locality = 6,
            /// <summary>
            /// Enum Suburb for value: suburb
            /// </summary>
            [EnumMember(Value = "suburb")]
            Suburb = 7,
            /// <summary>
            /// Enum Address for value: address
            /// </summary>
            [EnumMember(Value = "address")]
            Address = 8,
            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown = 9        }
        /// <summary>
        /// This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. 
        /// </summary>
        /// <value>This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StopFinderLocation" /> class.
        /// </summary>
        /// <param name="assignedStops">This is a list of stops that are assigned to this location. This means if you&#x27;re in the current location and want to catch public transport, these assigned stops are directly available to you. .</param>
        /// <param name="buildingNumber">This is the number of the property, included only if the &#x60;type&#x60; value is set to &#x60;singlehouse&#x60;. Note that it is a string, as it may include non-numeric characters. .</param>
        /// <param name="coord">Contains exactly two values: the first value is the latitude, the second value is the longitude. .</param>
        /// <param name="disassembledName">This is the short version of the location name, which does not include the suburb or other information. .</param>
        /// <param name="id">This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. .</param>
        /// <param name="isBest">Indicates whether or not this is the best match out of all the returned locations..</param>
        /// <param name="isGlobalId">This determines whether the id property is a global stop id or not .</param>
        /// <param name="matchQuality">This value indicates how well the returned stop matches the search query. A higher number indicates a better match..</param>
        /// <param name="modes">This is included only if the &#x60;type&#x60; value is set to &#x60;stop&#x60;. Contains a list of modes of transport that service this stop. This can be useful for showing relevant wayfinding icons when presenting users with a list of matching stops to choose from.  The following values may be present:  * &#x60;1&#x60;: Train * &#x60;2&#x60;: Metro * &#x60;4&#x60;: Light Rail * &#x60;5&#x60;: Bus * &#x60;7&#x60;: Coach * &#x60;9&#x60;: Ferry * &#x60;11&#x60;: School Bus .</param>
        /// <param name="name">This is the long version of the location name, which may include the suburb or other information. .</param>
        /// <param name="parent">parent.</param>
        /// <param name="streetName">This is included only if the &#x60;type&#x60; value is set to &#x60;street&#x60; or &#x60;singlehouse&#x60;..</param>
        /// <param name="type">This is the type of location being returned. It may represent a stop or platform that a public transport service physically stops at for passenger boarding, or it may represent somebody&#x27;s house. A value of &#x60;unknown&#x60; likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it. .</param>
        public StopFinderLocation(List<StopFinderAssignedStop> assignedStops = default, string buildingNumber = default, List<double?> coord = default, string disassembledName = default, string id = default, bool? isBest = default, bool? isGlobalId = default, int? matchQuality = default, List<int?> modes = default, string name = default, ParentLocation parent = default, string streetName = default, TypeEnum? type = default)
        {
            AssignedStops = assignedStops;
            BuildingNumber = buildingNumber;
            Coord = coord;
            DisassembledName = disassembledName;
            Id = id;
            IsBest = isBest;
            IsGlobalId = isGlobalId;
            MatchQuality = matchQuality;
            Modes = modes;
            Name = name;
            Parent = parent;
            StreetName = streetName;
            Type = type;
        }
        
        /// <summary>
        /// This is a list of stops that are assigned to this location. This means if you&#x27;re in the current location and want to catch public transport, these assigned stops are directly available to you. 
        /// </summary>
        /// <value>This is a list of stops that are assigned to this location. This means if you&#x27;re in the current location and want to catch public transport, these assigned stops are directly available to you. </value>
        [DataMember(Name="assignedStops", EmitDefaultValue=false)]
        public List<StopFinderAssignedStop> AssignedStops { get; set; }

        /// <summary>
        /// This is the number of the property, included only if the &#x60;type&#x60; value is set to &#x60;singlehouse&#x60;. Note that it is a string, as it may include non-numeric characters. 
        /// </summary>
        /// <value>This is the number of the property, included only if the &#x60;type&#x60; value is set to &#x60;singlehouse&#x60;. Note that it is a string, as it may include non-numeric characters. </value>
        [DataMember(Name="buildingNumber", EmitDefaultValue=false)]
        public string BuildingNumber { get; set; }

        /// <summary>
        /// Contains exactly two values: the first value is the latitude, the second value is the longitude. 
        /// </summary>
        /// <value>Contains exactly two values: the first value is the latitude, the second value is the longitude. </value>
        [DataMember(Name="coord", EmitDefaultValue=false)]
        public List<double?> Coord { get; set; }

        /// <summary>
        /// This is the short version of the location name, which does not include the suburb or other information. 
        /// </summary>
        /// <value>This is the short version of the location name, which does not include the suburb or other information. </value>
        [DataMember(Name="disassembledName", EmitDefaultValue=false)]
        public string DisassembledName { get; set; }

        /// <summary>
        /// This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. 
        /// </summary>
        /// <value>This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with &#x60;stop_finder&#x60;, or can be used as the origin or destination in an &#x60;trip&#x60; request. The format of a location ID differs greatly, depending on the type of location it is. </value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Indicates whether or not this is the best match out of all the returned locations.
        /// </summary>
        /// <value>Indicates whether or not this is the best match out of all the returned locations.</value>
        [DataMember(Name="isBest", EmitDefaultValue=false)]
        public bool? IsBest { get; set; }

        /// <summary>
        /// This determines whether the id property is a global stop id or not 
        /// </summary>
        /// <value>This determines whether the id property is a global stop id or not </value>
        [DataMember(Name="isGlobalId", EmitDefaultValue=false)]
        public bool? IsGlobalId { get; set; }

        /// <summary>
        /// This value indicates how well the returned stop matches the search query. A higher number indicates a better match.
        /// </summary>
        /// <value>This value indicates how well the returned stop matches the search query. A higher number indicates a better match.</value>
        [DataMember(Name="matchQuality", EmitDefaultValue=false)]
        public int? MatchQuality { get; set; }

        /// <summary>
        /// This is included only if the &#x60;type&#x60; value is set to &#x60;stop&#x60;. Contains a list of modes of transport that service this stop. This can be useful for showing relevant wayfinding icons when presenting users with a list of matching stops to choose from.  The following values may be present:  * &#x60;1&#x60;: Train * &#x60;2&#x60;: Metro * &#x60;4&#x60;: Light Rail * &#x60;5&#x60;: Bus * &#x60;7&#x60;: Coach * &#x60;9&#x60;: Ferry * &#x60;11&#x60;: School Bus 
        /// </summary>
        /// <value>This is included only if the &#x60;type&#x60; value is set to &#x60;stop&#x60;. Contains a list of modes of transport that service this stop. This can be useful for showing relevant wayfinding icons when presenting users with a list of matching stops to choose from.  The following values may be present:  * &#x60;1&#x60;: Train * &#x60;2&#x60;: Metro * &#x60;4&#x60;: Light Rail * &#x60;5&#x60;: Bus * &#x60;7&#x60;: Coach * &#x60;9&#x60;: Ferry * &#x60;11&#x60;: School Bus </value>
        [DataMember(Name="modes", EmitDefaultValue=false)]
        public List<int?> Modes { get; set; }

        /// <summary>
        /// This is the long version of the location name, which may include the suburb or other information. 
        /// </summary>
        /// <value>This is the long version of the location name, which may include the suburb or other information. </value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Parent
        /// </summary>
        [DataMember(Name="parent", EmitDefaultValue=false)]
        public ParentLocation Parent { get; set; }

        /// <summary>
        /// This is included only if the &#x60;type&#x60; value is set to &#x60;street&#x60; or &#x60;singlehouse&#x60;.
        /// </summary>
        /// <value>This is included only if the &#x60;type&#x60; value is set to &#x60;street&#x60; or &#x60;singlehouse&#x60;.</value>
        [DataMember(Name="streetName", EmitDefaultValue=false)]
        public string StreetName { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StopFinderLocation {\n");
            sb.Append("  AssignedStops: ").Append(AssignedStops).Append("\n");
            sb.Append("  BuildingNumber: ").Append(BuildingNumber).Append("\n");
            sb.Append("  Coord: ").Append(Coord).Append("\n");
            sb.Append("  DisassembledName: ").Append(DisassembledName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsBest: ").Append(IsBest).Append("\n");
            sb.Append("  IsGlobalId: ").Append(IsGlobalId).Append("\n");
            sb.Append("  MatchQuality: ").Append(MatchQuality).Append("\n");
            sb.Append("  Modes: ").Append(Modes).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  StreetName: ").Append(StreetName).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as StopFinderLocation);
        }

        /// <summary>
        /// Returns true if StopFinderLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of StopFinderLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StopFinderLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    AssignedStops == input.AssignedStops ||
                    AssignedStops != null &&
                    input.AssignedStops != null &&
                    AssignedStops.SequenceEqual(input.AssignedStops)
                ) && 
                (
                    BuildingNumber == input.BuildingNumber ||
                    BuildingNumber != null &&
                    BuildingNumber.Equals(input.BuildingNumber)
                ) && 
                (
                    Coord == input.Coord ||
                    Coord != null &&
                    input.Coord != null &&
                    Coord.SequenceEqual(input.Coord)
                ) && 
                (
                    DisassembledName == input.DisassembledName ||
                    DisassembledName != null &&
                    DisassembledName.Equals(input.DisassembledName)
                ) && 
                (
                    Id == input.Id ||
                    Id != null &&
                    Id.Equals(input.Id)
                ) && 
                (
                    IsBest == input.IsBest ||
                    IsBest != null &&
                    IsBest.Equals(input.IsBest)
                ) && 
                (
                    IsGlobalId == input.IsGlobalId ||
                    IsGlobalId != null &&
                    IsGlobalId.Equals(input.IsGlobalId)
                ) && 
                (
                    MatchQuality == input.MatchQuality ||
                    MatchQuality != null &&
                    MatchQuality.Equals(input.MatchQuality)
                ) && 
                (
                    Modes == input.Modes ||
                    Modes != null &&
                    input.Modes != null &&
                    Modes.SequenceEqual(input.Modes)
                ) && 
                (
                    Name == input.Name ||
                    Name != null &&
                    Name.Equals(input.Name)
                ) && 
                (
                    Parent == input.Parent ||
                    Parent != null &&
                    Parent.Equals(input.Parent)
                ) && 
                (
                    StreetName == input.StreetName ||
                    StreetName != null &&
                    StreetName.Equals(input.StreetName)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (AssignedStops != null)
                    hashCode = hashCode * 59 + AssignedStops.GetHashCode();
                if (BuildingNumber != null)
                    hashCode = hashCode * 59 + BuildingNumber.GetHashCode();
                if (Coord != null)
                    hashCode = hashCode * 59 + Coord.GetHashCode();
                if (DisassembledName != null)
                    hashCode = hashCode * 59 + DisassembledName.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (IsBest != null)
                    hashCode = hashCode * 59 + IsBest.GetHashCode();
                if (IsGlobalId != null)
                    hashCode = hashCode * 59 + IsGlobalId.GetHashCode();
                if (MatchQuality != null)
                    hashCode = hashCode * 59 + MatchQuality.GetHashCode();
                if (Modes != null)
                    hashCode = hashCode * 59 + Modes.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Parent != null)
                    hashCode = hashCode * 59 + Parent.GetHashCode();
                if (StreetName != null)
                    hashCode = hashCode * 59 + StreetName.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
