/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Contains additional information about this journey leg, such as wheelchair accessibility information. 
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegProperties :  IEquatable<TripRequestResponseJourneyLegProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegProperties" /> class.
        /// </summary>
        /// <param name="dIFFERENTFARES">XXX.</param>
        /// <param name="planLowFloorVehicle">This indicates whether or not the vehicle is wheelchair accessible..</param>
        /// <param name="planWheelChairAccess">This indicates whether or not the stop is wheelchair accessible..</param>
        /// <param name="lineType">XXX seen a value of SUPPLEMENT for ferry route .</param>
        /// <param name="vehicleAccess">This value is not currently in use..</param>
        public TripRequestResponseJourneyLegProperties(string dIFFERENTFARES = default, string planLowFloorVehicle = default, string planWheelChairAccess = default, string lineType = default, List<string> vehicleAccess = default)
        {
            DIFFERENT_FARES = dIFFERENTFARES;
            PlanLowFloorVehicle = planLowFloorVehicle;
            PlanWheelChairAccess = planWheelChairAccess;
            LineType = lineType;
            VehicleAccess = vehicleAccess;
        }
        
        /// <summary>
        /// XXX
        /// </summary>
        /// <value>XXX</value>
        [DataMember(Name="DIFFERENT_FARES", EmitDefaultValue=false)]
        public string DIFFERENT_FARES { get; set; }

        /// <summary>
        /// This indicates whether or not the vehicle is wheelchair accessible.
        /// </summary>
        /// <value>This indicates whether or not the vehicle is wheelchair accessible.</value>
        [DataMember(Name="PlanLowFloorVehicle", EmitDefaultValue=false)]
        public string PlanLowFloorVehicle { get; set; }

        /// <summary>
        /// This indicates whether or not the stop is wheelchair accessible.
        /// </summary>
        /// <value>This indicates whether or not the stop is wheelchair accessible.</value>
        [DataMember(Name="PlanWheelChairAccess", EmitDefaultValue=false)]
        public string PlanWheelChairAccess { get; set; }

        /// <summary>
        /// XXX seen a value of SUPPLEMENT for ferry route 
        /// </summary>
        /// <value>XXX seen a value of SUPPLEMENT for ferry route </value>
        [DataMember(Name="lineType", EmitDefaultValue=false)]
        public string LineType { get; set; }

        /// <summary>
        /// This value is not currently in use.
        /// </summary>
        /// <value>This value is not currently in use.</value>
        [DataMember(Name="vehicleAccess", EmitDefaultValue=false)]
        public List<string> VehicleAccess { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegProperties {\n");
            sb.Append("  DIFFERENT_FARES: ").Append(DIFFERENT_FARES).Append("\n");
            sb.Append("  PlanLowFloorVehicle: ").Append(PlanLowFloorVehicle).Append("\n");
            sb.Append("  PlanWheelChairAccess: ").Append(PlanWheelChairAccess).Append("\n");
            sb.Append("  LineType: ").Append(LineType).Append("\n");
            sb.Append("  VehicleAccess: ").Append(VehicleAccess).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegProperties);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegProperties input)
        {
            if (input == null)
                return false;

            return 
                (
                    DIFFERENT_FARES == input.DIFFERENT_FARES ||
                    DIFFERENT_FARES != null &&
                    DIFFERENT_FARES.Equals(input.DIFFERENT_FARES)
                ) && 
                (
                    PlanLowFloorVehicle == input.PlanLowFloorVehicle ||
                    PlanLowFloorVehicle != null &&
                    PlanLowFloorVehicle.Equals(input.PlanLowFloorVehicle)
                ) && 
                (
                    PlanWheelChairAccess == input.PlanWheelChairAccess ||
                    PlanWheelChairAccess != null &&
                    PlanWheelChairAccess.Equals(input.PlanWheelChairAccess)
                ) && 
                (
                    LineType == input.LineType ||
                    LineType != null &&
                    LineType.Equals(input.LineType)
                ) && 
                (
                    VehicleAccess == input.VehicleAccess ||
                    VehicleAccess != null &&
                    input.VehicleAccess != null &&
                    VehicleAccess.SequenceEqual(input.VehicleAccess)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (DIFFERENT_FARES != null)
                    hashCode = hashCode * 59 + DIFFERENT_FARES.GetHashCode();
                if (PlanLowFloorVehicle != null)
                    hashCode = hashCode * 59 + PlanLowFloorVehicle.GetHashCode();
                if (PlanWheelChairAccess != null)
                    hashCode = hashCode * 59 + PlanWheelChairAccess.GetHashCode();
                if (LineType != null)
                    hashCode = hashCode * 59 + LineType.GetHashCode();
                if (VehicleAccess != null)
                    hashCode = hashCode * 59 + VehicleAccess.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
