/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This object describes walking directions for interchanging between two consecutive legs. This occurs in the case when there&#x27;s only a small distance between two transit legs, not enough to constitute a standalone walking leg. 
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegInterchange :  IEquatable<TripRequestResponseJourneyLegInterchange>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegInterchange" /> class.
        /// </summary>
        /// <param name="coords">This is a list of coordinates that makes up the path of the interchange. .</param>
        /// <param name="desc">This is a description of the interchange. .</param>
        /// <param name="type">This indicates the mode of travel for the interchange. Both &#x60;99&#x60; and &#x60;100&#x60; indicate walking. .</param>
        public TripRequestResponseJourneyLegInterchange(List<List<double?>> coords = default, string desc = default, int? type = default)
        {
            Coords = coords;
            Desc = desc;
            Type = type;
        }
        
        /// <summary>
        /// This is a list of coordinates that makes up the path of the interchange. 
        /// </summary>
        /// <value>This is a list of coordinates that makes up the path of the interchange. </value>
        [DataMember(Name="coords", EmitDefaultValue=false)]
        public List<List<double?>> Coords { get; set; }

        /// <summary>
        /// This is a description of the interchange. 
        /// </summary>
        /// <value>This is a description of the interchange. </value>
        [DataMember(Name="desc", EmitDefaultValue=false)]
        public string Desc { get; set; }

        /// <summary>
        /// This indicates the mode of travel for the interchange. Both &#x60;99&#x60; and &#x60;100&#x60; indicate walking. 
        /// </summary>
        /// <value>This indicates the mode of travel for the interchange. Both &#x60;99&#x60; and &#x60;100&#x60; indicate walking. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public int? Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegInterchange {\n");
            sb.Append("  Coords: ").Append(Coords).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegInterchange);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegInterchange instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegInterchange to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegInterchange input)
        {
            if (input == null)
                return false;

            return 
                (
                    Coords == input.Coords ||
                    Coords != null &&
                    input.Coords != null &&
                    Coords.SequenceEqual(input.Coords)
                ) && 
                (
                    Desc == input.Desc ||
                    Desc != null &&
                    Desc.Equals(input.Desc)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Coords != null)
                    hashCode = hashCode * 59 + Coords.GetHashCode();
                if (Desc != null)
                    hashCode = hashCode * 59 + Desc.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
