/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element describes a starting or finishing point for a walking instruction.
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation :  IEquatable<TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation" /> class.
        /// </summary>
        /// <param name="area">This is an internal value used to group stops together..</param>
        /// <param name="georef">This is an identifier for this particular instruction / location, based on its location. .</param>
        /// <param name="location">location.</param>
        /// <param name="platform">If available, this is a platform number that relates to this instruction. It defaults to &#x60;0&#x60; if there is no such information available. .</param>
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation(int? area = default, string georef = default, TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation location = default, int? platform = default)
        {
            Area = area;
            Georef = georef;
            Location = location;
            Platform = platform;
        }
        
        /// <summary>
        /// This is an internal value used to group stops together.
        /// </summary>
        /// <value>This is an internal value used to group stops together.</value>
        [DataMember(Name="area", EmitDefaultValue=false)]
        public int? Area { get; set; }

        /// <summary>
        /// This is an identifier for this particular instruction / location, based on its location. 
        /// </summary>
        /// <value>This is an identifier for this particular instruction / location, based on its location. </value>
        [DataMember(Name="georef", EmitDefaultValue=false)]
        public string Georef { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation Location { get; set; }

        /// <summary>
        /// If available, this is a platform number that relates to this instruction. It defaults to &#x60;0&#x60; if there is no such information available. 
        /// </summary>
        /// <value>If available, this is a platform number that relates to this instruction. It defaults to &#x60;0&#x60; if there is no such information available. </value>
        [DataMember(Name="platform", EmitDefaultValue=false)]
        public int? Platform { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {\n");
            sb.Append("  Area: ").Append(Area).Append("\n");
            sb.Append("  Georef: ").Append(Georef).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    Area == input.Area ||
                    Area != null &&
                    Area.Equals(input.Area)
                ) && 
                (
                    Georef == input.Georef ||
                    Georef != null &&
                    Georef.Equals(input.Georef)
                ) && 
                (
                    Location == input.Location ||
                    Location != null &&
                    Location.Equals(input.Location)
                ) && 
                (
                    Platform == input.Platform ||
                    Platform != null &&
                    Platform.Equals(input.Platform)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Area != null)
                    hashCode = hashCode * 59 + Area.GetHashCode();
                if (Georef != null)
                    hashCode = hashCode * 59 + Georef.GetHashCode();
                if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                if (Platform != null)
                    hashCode = hashCode * 59 + Platform.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
