/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// The element describes a single walking instruction.
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegStopFootpathInfoFootpathElem :  IEquatable<TripRequestResponseJourneyLegStopFootpathInfoFootpathElem>, IValidatableObject
    {
        /// <summary>
        /// Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go &#x60;UP&#x60; or &#x60;DOWN&#x60; to a different floor. This value will be &#x60;LEVEL&#x60; when the &#x60;type&#x60; field is also &#x60;LEVEL&#x60;. 
        /// </summary>
        /// <value>Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go &#x60;UP&#x60; or &#x60;DOWN&#x60; to a different floor. This value will be &#x60;LEVEL&#x60; when the &#x60;type&#x60; field is also &#x60;LEVEL&#x60;. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum LevelEnum
        {
            /// <summary>
            /// Enum DOWN for value: DOWN
            /// </summary>
            [EnumMember(Value = "DOWN")]
            DOWN = 1,
            /// <summary>
            /// Enum LEVEL for value: LEVEL
            /// </summary>
            [EnumMember(Value = "LEVEL")]
            LEVEL = 2,
            /// <summary>
            /// Enum UP for value: UP
            /// </summary>
            [EnumMember(Value = "UP")]
            UP = 3        }
        /// <summary>
        /// Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go &#x60;UP&#x60; or &#x60;DOWN&#x60; to a different floor. This value will be &#x60;LEVEL&#x60; when the &#x60;type&#x60; field is also &#x60;LEVEL&#x60;. 
        /// </summary>
        /// <value>Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go &#x60;UP&#x60; or &#x60;DOWN&#x60; to a different floor. This value will be &#x60;LEVEL&#x60; when the &#x60;type&#x60; field is also &#x60;LEVEL&#x60;. </value>
        [DataMember(Name="level", EmitDefaultValue=false)]
        public LevelEnum? Level { get; set; }
        /// <summary>
        /// This indicates the type of \&quot;terrain\&quot; for this instruction. &#x60;LEVEL&#x60; indicates a normal flat surface. 
        /// </summary>
        /// <value>This indicates the type of \&quot;terrain\&quot; for this instruction. &#x60;LEVEL&#x60; indicates a normal flat surface. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum ESCALATOR for value: ESCALATOR
            /// </summary>
            [EnumMember(Value = "ESCALATOR")]
            ESCALATOR = 1,
            /// <summary>
            /// Enum ELEVATOR for value: ELEVATOR
            /// </summary>
            [EnumMember(Value = "ELEVATOR")]
            ELEVATOR = 2,
            /// <summary>
            /// Enum STAIRS for value: STAIRS
            /// </summary>
            [EnumMember(Value = "STAIRS")]
            STAIRS = 3,
            /// <summary>
            /// Enum LEVEL for value: LEVEL
            /// </summary>
            [EnumMember(Value = "LEVEL")]
            LEVEL = 4,
            /// <summary>
            /// Enum RAMP for value: RAMP
            /// </summary>
            [EnumMember(Value = "RAMP")]
            RAMP = 5        }
        /// <summary>
        /// This indicates the type of \&quot;terrain\&quot; for this instruction. &#x60;LEVEL&#x60; indicates a normal flat surface. 
        /// </summary>
        /// <value>This indicates the type of \&quot;terrain\&quot; for this instruction. &#x60;LEVEL&#x60; indicates a normal flat surface. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegStopFootpathInfoFootpathElem" /> class.
        /// </summary>
        /// <param name="description">Contains additional information about this instruction, but is generally unused. .</param>
        /// <param name="destination">destination.</param>
        /// <param name="level">Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go &#x60;UP&#x60; or &#x60;DOWN&#x60; to a different floor. This value will be &#x60;LEVEL&#x60; when the &#x60;type&#x60; field is also &#x60;LEVEL&#x60;. .</param>
        /// <param name="levelFrom">Indicates the floor number the instruction is starting from. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. .</param>
        /// <param name="levelTo">Indicates the floor number the instruction ends of. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. .</param>
        /// <param name="origin">origin.</param>
        /// <param name="type">This indicates the type of \&quot;terrain\&quot; for this instruction. &#x60;LEVEL&#x60; indicates a normal flat surface. .</param>
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElem(string description = default, TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation destination = default, LevelEnum? level = default, int? levelFrom = default, int? levelTo = default, TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation origin = default, TypeEnum? type = default)
        {
            Description = description;
            Destination = destination;
            Level = level;
            LevelFrom = levelFrom;
            LevelTo = levelTo;
            Origin = origin;
            Type = type;
        }
        
        /// <summary>
        /// Contains additional information about this instruction, but is generally unused. 
        /// </summary>
        /// <value>Contains additional information about this instruction, but is generally unused. </value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Destination
        /// </summary>
        [DataMember(Name="destination", EmitDefaultValue=false)]
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation Destination { get; set; }


        /// <summary>
        /// Indicates the floor number the instruction is starting from. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. 
        /// </summary>
        /// <value>Indicates the floor number the instruction is starting from. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. </value>
        [DataMember(Name="levelFrom", EmitDefaultValue=false)]
        public int? LevelFrom { get; set; }

        /// <summary>
        /// Indicates the floor number the instruction ends of. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. 
        /// </summary>
        /// <value>Indicates the floor number the instruction ends of. If the &#x60;type&#x60; is &#x60;LEVEL&#x60;, then the &#x60;levelFrom&#x60; and &#x60;levelTo&#x60; values should be the same. </value>
        [DataMember(Name="levelTo", EmitDefaultValue=false)]
        public int? LevelTo { get; set; }

        /// <summary>
        /// Gets or Sets Origin
        /// </summary>
        [DataMember(Name="origin", EmitDefaultValue=false)]
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation Origin { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Destination: ").Append(Destination).Append("\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  LevelFrom: ").Append(LevelFrom).Append("\n");
            sb.Append("  LevelTo: ").Append(LevelTo).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegStopFootpathInfoFootpathElem);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegStopFootpathInfoFootpathElem instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegStopFootpathInfoFootpathElem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegStopFootpathInfoFootpathElem input)
        {
            if (input == null)
                return false;

            return 
                (
                    Description == input.Description ||
                    Description != null &&
                    Description.Equals(input.Description)
                ) && 
                (
                    Destination == input.Destination ||
                    Destination != null &&
                    Destination.Equals(input.Destination)
                ) && 
                (
                    Level == input.Level ||
                    Level != null &&
                    Level.Equals(input.Level)
                ) && 
                (
                    LevelFrom == input.LevelFrom ||
                    LevelFrom != null &&
                    LevelFrom.Equals(input.LevelFrom)
                ) && 
                (
                    LevelTo == input.LevelTo ||
                    LevelTo != null &&
                    LevelTo.Equals(input.LevelTo)
                ) && 
                (
                    Origin == input.Origin ||
                    Origin != null &&
                    Origin.Equals(input.Origin)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                if (Destination != null)
                    hashCode = hashCode * 59 + Destination.GetHashCode();
                if (Level != null)
                    hashCode = hashCode * 59 + Level.GetHashCode();
                if (LevelFrom != null)
                    hashCode = hashCode * 59 + LevelFrom.GetHashCode();
                if (LevelTo != null)
                    hashCode = hashCode * 59 + LevelTo.GetHashCode();
                if (Origin != null)
                    hashCode = hashCode * 59 + Origin.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
