/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Describes a single download available for this journey stop.
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegStopDownload :  IEquatable<TripRequestResponseJourneyLegStopDownload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegStopDownload" /> class.
        /// </summary>
        /// <param name="type">This indicates what type of download this is. For example, &#x60;RM&#x60; refers to Route Map. .</param>
        /// <param name="url">This is the URL for the download. .</param>
        public TripRequestResponseJourneyLegStopDownload(string type = default, string url = default)
        {
            Type = type;
            Url = url;
        }
        
        /// <summary>
        /// This indicates what type of download this is. For example, &#x60;RM&#x60; refers to Route Map. 
        /// </summary>
        /// <value>This indicates what type of download this is. For example, &#x60;RM&#x60; refers to Route Map. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// This is the URL for the download. 
        /// </summary>
        /// <value>This is the URL for the download. </value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegStopDownload {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegStopDownload);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegStopDownload instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegStopDownload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegStopDownload input)
        {
            if (input == null)
                return false;

            return 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                ) && 
                (
                    Url == input.Url ||
                    Url != null &&
                    Url.Equals(input.Url)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
