/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Contains additional properties about this route. 
    /// </summary>
    [DataContract]
        public partial class TripTransportationProperties :  IEquatable<TripTransportationProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripTransportationProperties" /> class.
        /// </summary>
        /// <param name="isTTB">XXX.</param>
        /// <param name="tripCode">This is an ID for this journey option..</param>
        public TripTransportationProperties(bool? isTTB = default, int? tripCode = default)
        {
            IsTTB = isTTB;
            TripCode = tripCode;
        }
        
        /// <summary>
        /// XXX
        /// </summary>
        /// <value>XXX</value>
        [DataMember(Name="isTTB", EmitDefaultValue=false)]
        public bool? IsTTB { get; set; }

        /// <summary>
        /// This is an ID for this journey option.
        /// </summary>
        /// <value>This is an ID for this journey option.</value>
        [DataMember(Name="tripCode", EmitDefaultValue=false)]
        public int? TripCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripTransportationProperties {\n");
            sb.Append("  IsTTB: ").Append(IsTTB).Append("\n");
            sb.Append("  TripCode: ").Append(TripCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripTransportationProperties);
        }

        /// <summary>
        /// Returns true if TripTransportationProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of TripTransportationProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripTransportationProperties input)
        {
            if (input == null)
                return false;

            return 
                (
                    IsTTB == input.IsTTB ||
                    IsTTB != null &&
                    IsTTB.Equals(input.IsTTB)
                ) && 
                (
                    TripCode == input.TripCode ||
                    TripCode != null &&
                    TripCode.Equals(input.TripCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (IsTTB != null)
                    hashCode = hashCode * 59 + IsTTB.GetHashCode();
                if (TripCode != null)
                    hashCode = hashCode * 59 + TripCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
