/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This includes information about the location in which this instruction takes place. 
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation :  IEquatable<TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation>, IValidatableObject
    {
        /// <summary>
        /// This is the type of location in which this instruction occurs.
        /// </summary>
        /// <value>This is the type of location in which this instruction occurs.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Poi for value: poi
            /// </summary>
            [EnumMember(Value = "poi")]
            Poi = 1,
            /// <summary>
            /// Enum Singlehouse for value: singlehouse
            /// </summary>
            [EnumMember(Value = "singlehouse")]
            Singlehouse = 2,
            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 3,
            /// <summary>
            /// Enum Platform for value: platform
            /// </summary>
            [EnumMember(Value = "platform")]
            Platform = 4,
            /// <summary>
            /// Enum Street for value: street
            /// </summary>
            [EnumMember(Value = "street")]
            Street = 5,
            /// <summary>
            /// Enum Locality for value: locality
            /// </summary>
            [EnumMember(Value = "locality")]
            Locality = 6,
            /// <summary>
            /// Enum Suburb for value: suburb
            /// </summary>
            [EnumMember(Value = "suburb")]
            Suburb = 7,
            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown = 8        }
        /// <summary>
        /// This is the type of location in which this instruction occurs.
        /// </summary>
        /// <value>This is the type of location in which this instruction occurs.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation" /> class.
        /// </summary>
        /// <param name="coord">Contains exactly two values: the first value is the latitude, the second value is the longitude. Although multiple instructions may reference the same location, this coordinate is specific to this particular instruction. .</param>
        /// <param name="id">This the unique ID for the stop in which this instruction occurs..</param>
        /// <param name="type">This is the type of location in which this instruction occurs..</param>
        public TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation(List<double?> coord = default, string id = default, TypeEnum? type = default)
        {
            Coord = coord;
            Id = id;
            Type = type;
        }
        
        /// <summary>
        /// Contains exactly two values: the first value is the latitude, the second value is the longitude. Although multiple instructions may reference the same location, this coordinate is specific to this particular instruction. 
        /// </summary>
        /// <value>Contains exactly two values: the first value is the latitude, the second value is the longitude. Although multiple instructions may reference the same location, this coordinate is specific to this particular instruction. </value>
        [DataMember(Name="coord", EmitDefaultValue=false)]
        public List<double?> Coord { get; set; }

        /// <summary>
        /// This the unique ID for the stop in which this instruction occurs.
        /// </summary>
        /// <value>This the unique ID for the stop in which this instruction occurs.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {\n");
            sb.Append("  Coord: ").Append(Coord).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    Coord == input.Coord ||
                    Coord != null &&
                    input.Coord != null &&
                    Coord.SequenceEqual(input.Coord)
                ) && 
                (
                    Id == input.Id ||
                    Id != null &&
                    Id.Equals(input.Id)
                ) && 
                (
                    Type == input.Type ||
                    Type != null &&
                    Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Coord != null)
                    hashCode = hashCode * 59 + Coord.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
