/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace TfNSWOpenData.Models
{
    /// <summary>
    /// Contains a single instruction for completing a walking leg associated with a journey leg.
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourneyLegPathDescription :  IEquatable<TripRequestResponseJourneyLegPathDescription>, IValidatableObject
    {
        /// <summary>
        /// Indicates what you have to do (in addition the turn &#x60;turnDirection&#x60;) to execute this step of the path description. 
        /// </summary>
        /// <value>Indicates what you have to do (in addition the turn &#x60;turnDirection&#x60;) to execute this step of the path description. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ManoeuvreEnum
        {
            /// <summary>
            /// Enum LEAVE for value: LEAVE
            /// </summary>
            [EnumMember(Value = "LEAVE")]
            LEAVE = 1,
            /// <summary>
            /// Enum KEEP for value: KEEP
            /// </summary>
            [EnumMember(Value = "KEEP")]
            KEEP = 2,
            /// <summary>
            /// Enum TURN for value: TURN
            /// </summary>
            [EnumMember(Value = "TURN")]
            TURN = 3,
            /// <summary>
            /// Enum ENTER for value: ENTER
            /// </summary>
            [EnumMember(Value = "ENTER")]
            ENTER = 4,
            /// <summary>
            /// Enum CONTINUE for value: CONTINUE
            /// </summary>
            [EnumMember(Value = "CONTINUE")]
            CONTINUE = 5        }
        /// <summary>
        /// Indicates what you have to do (in addition the turn &#x60;turnDirection&#x60;) to execute this step of the path description. 
        /// </summary>
        /// <value>Indicates what you have to do (in addition the turn &#x60;turnDirection&#x60;) to execute this step of the path description. </value>
        [DataMember(Name="manoeuvre", EmitDefaultValue=false)]
        public ManoeuvreEnum? Manoeuvre { get; set; }
        /// <summary>
        /// Indicates the way you need to turn to execute this step of the path description. 
        /// </summary>
        /// <value>Indicates the way you need to turn to execute this step of the path description. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TurnDirectionEnum
        {
            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWN = 1,
            /// <summary>
            /// Enum STRAIGHT for value: STRAIGHT
            /// </summary>
            [EnumMember(Value = "STRAIGHT")]
            STRAIGHT = 2,
            /// <summary>
            /// Enum RIGHT for value: RIGHT
            /// </summary>
            [EnumMember(Value = "RIGHT")]
            RIGHT = 3,
            /// <summary>
            /// Enum LEFT for value: LEFT
            /// </summary>
            [EnumMember(Value = "LEFT")]
            LEFT = 4,
            /// <summary>
            /// Enum SLIGHTRIGHT for value: SLIGHT_RIGHT
            /// </summary>
            [EnumMember(Value = "SLIGHT_RIGHT")]
            SLIGHTRIGHT = 5,
            /// <summary>
            /// Enum SLIGHTLEFT for value: SLIGHT_LEFT
            /// </summary>
            [EnumMember(Value = "SLIGHT_LEFT")]
            SLIGHTLEFT = 6,
            /// <summary>
            /// Enum SHARPLEFT for value: SHARP_LEFT
            /// </summary>
            [EnumMember(Value = "SHARP_LEFT")]
            SHARPLEFT = 7,
            /// <summary>
            /// Enum SHARPRIGHT for value: SHARP_RIGHT
            /// </summary>
            [EnumMember(Value = "SHARP_RIGHT")]
            SHARPRIGHT = 8        }
        /// <summary>
        /// Indicates the way you need to turn to execute this step of the path description. 
        /// </summary>
        /// <value>Indicates the way you need to turn to execute this step of the path description. </value>
        [DataMember(Name="turnDirection", EmitDefaultValue=false)]
        public TurnDirectionEnum? TurnDirection { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourneyLegPathDescription" /> class.
        /// </summary>
        /// <param name="coord">Contains exactly two values: the first value is the latitude, the second value is the longitude. This is the location where the instruction occurs. .</param>
        /// <param name="cumDistance">This is the cumulative distance travelled in metres at the point of this step..</param>
        /// <param name="cumDuration">This is the cumulative duration in seconds at the point of this step. .</param>
        /// <param name="distance">This is the distance travelled in this step in metres. .</param>
        /// <param name="distanceDown">This is the distance travelled downward in this step in metres .</param>
        /// <param name="distanceUp">This is the distance travelled upward in this step in metres .</param>
        /// <param name="duration">This is the duration of this step in seconds. .</param>
        /// <param name="fromCoordsIndex">This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, starting from this index. .</param>
        /// <param name="manoeuvre">Indicates what you have to do (in addition the turn &#x60;turnDirection&#x60;) to execute this step of the path description. .</param>
        /// <param name="name">This is a specific description of what to do. In some cases, this information is required in addition to the other properties provided in this step. .</param>
        /// <param name="skyDirection">The direction in degrees (0-359) of the skyDirection.</param>
        /// <param name="toCoordsIndex">This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, ending at this index. .</param>
        /// <param name="turnDirection">Indicates the way you need to turn to execute this step of the path description. .</param>
        public TripRequestResponseJourneyLegPathDescription(List<double?> coord = default, int? cumDistance = default, int? cumDuration = default, int? distance = default, int? distanceDown = default, int? distanceUp = default, int? duration = default, int? fromCoordsIndex = default, ManoeuvreEnum? manoeuvre = default, string name = default, int? skyDirection = default, int? toCoordsIndex = default, TurnDirectionEnum? turnDirection = default)
        {
            Coord = coord;
            CumDistance = cumDistance;
            CumDuration = cumDuration;
            Distance = distance;
            DistanceDown = distanceDown;
            DistanceUp = distanceUp;
            Duration = duration;
            FromCoordsIndex = fromCoordsIndex;
            Manoeuvre = manoeuvre;
            Name = name;
            SkyDirection = skyDirection;
            ToCoordsIndex = toCoordsIndex;
            TurnDirection = turnDirection;
        }
        
        /// <summary>
        /// Contains exactly two values: the first value is the latitude, the second value is the longitude. This is the location where the instruction occurs. 
        /// </summary>
        /// <value>Contains exactly two values: the first value is the latitude, the second value is the longitude. This is the location where the instruction occurs. </value>
        [DataMember(Name="coord", EmitDefaultValue=false)]
        public List<double?> Coord { get; set; }

        /// <summary>
        /// This is the cumulative distance travelled in metres at the point of this step.
        /// </summary>
        /// <value>This is the cumulative distance travelled in metres at the point of this step.</value>
        [DataMember(Name="cumDistance", EmitDefaultValue=false)]
        public int? CumDistance { get; set; }

        /// <summary>
        /// This is the cumulative duration in seconds at the point of this step. 
        /// </summary>
        /// <value>This is the cumulative duration in seconds at the point of this step. </value>
        [DataMember(Name="cumDuration", EmitDefaultValue=false)]
        public int? CumDuration { get; set; }

        /// <summary>
        /// This is the distance travelled in this step in metres. 
        /// </summary>
        /// <value>This is the distance travelled in this step in metres. </value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public int? Distance { get; set; }

        /// <summary>
        /// This is the distance travelled downward in this step in metres 
        /// </summary>
        /// <value>This is the distance travelled downward in this step in metres </value>
        [DataMember(Name="distanceDown", EmitDefaultValue=false)]
        public int? DistanceDown { get; set; }

        /// <summary>
        /// This is the distance travelled upward in this step in metres 
        /// </summary>
        /// <value>This is the distance travelled upward in this step in metres </value>
        [DataMember(Name="distanceUp", EmitDefaultValue=false)]
        public int? DistanceUp { get; set; }

        /// <summary>
        /// This is the duration of this step in seconds. 
        /// </summary>
        /// <value>This is the duration of this step in seconds. </value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public int? Duration { get; set; }

        /// <summary>
        /// This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, starting from this index. 
        /// </summary>
        /// <value>This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, starting from this index. </value>
        [DataMember(Name="fromCoordsIndex", EmitDefaultValue=false)]
        public int? FromCoordsIndex { get; set; }


        /// <summary>
        /// This is a specific description of what to do. In some cases, this information is required in addition to the other properties provided in this step. 
        /// </summary>
        /// <value>This is a specific description of what to do. In some cases, this information is required in addition to the other properties provided in this step. </value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The direction in degrees (0-359) of the skyDirection
        /// </summary>
        /// <value>The direction in degrees (0-359) of the skyDirection</value>
        [DataMember(Name="skyDirection", EmitDefaultValue=false)]
        public int? SkyDirection { get; set; }

        /// <summary>
        /// This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, ending at this index. 
        /// </summary>
        /// <value>This field enables you to retrieve multiple coordinates from the &#x60;coords&#x60; property, ending at this index. </value>
        [DataMember(Name="toCoordsIndex", EmitDefaultValue=false)]
        public int? ToCoordsIndex { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourneyLegPathDescription {\n");
            sb.Append("  Coord: ").Append(Coord).Append("\n");
            sb.Append("  CumDistance: ").Append(CumDistance).Append("\n");
            sb.Append("  CumDuration: ").Append(CumDuration).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  DistanceDown: ").Append(DistanceDown).Append("\n");
            sb.Append("  DistanceUp: ").Append(DistanceUp).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  FromCoordsIndex: ").Append(FromCoordsIndex).Append("\n");
            sb.Append("  Manoeuvre: ").Append(Manoeuvre).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SkyDirection: ").Append(SkyDirection).Append("\n");
            sb.Append("  ToCoordsIndex: ").Append(ToCoordsIndex).Append("\n");
            sb.Append("  TurnDirection: ").Append(TurnDirection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourneyLegPathDescription);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourneyLegPathDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourneyLegPathDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourneyLegPathDescription input)
        {
            if (input == null)
                return false;

            return 
                (
                    Coord == input.Coord ||
                    Coord != null &&
                    input.Coord != null &&
                    Coord.SequenceEqual(input.Coord)
                ) && 
                (
                    CumDistance == input.CumDistance ||
                    CumDistance != null &&
                    CumDistance.Equals(input.CumDistance)
                ) && 
                (
                    CumDuration == input.CumDuration ||
                    CumDuration != null &&
                    CumDuration.Equals(input.CumDuration)
                ) && 
                (
                    Distance == input.Distance ||
                    Distance != null &&
                    Distance.Equals(input.Distance)
                ) && 
                (
                    DistanceDown == input.DistanceDown ||
                    DistanceDown != null &&
                    DistanceDown.Equals(input.DistanceDown)
                ) && 
                (
                    DistanceUp == input.DistanceUp ||
                    DistanceUp != null &&
                    DistanceUp.Equals(input.DistanceUp)
                ) && 
                (
                    Duration == input.Duration ||
                    Duration != null &&
                    Duration.Equals(input.Duration)
                ) && 
                (
                    FromCoordsIndex == input.FromCoordsIndex ||
                    FromCoordsIndex != null &&
                    FromCoordsIndex.Equals(input.FromCoordsIndex)
                ) && 
                (
                    Manoeuvre == input.Manoeuvre ||
                    Manoeuvre != null &&
                    Manoeuvre.Equals(input.Manoeuvre)
                ) && 
                (
                    Name == input.Name ||
                    Name != null &&
                    Name.Equals(input.Name)
                ) && 
                (
                    SkyDirection == input.SkyDirection ||
                    SkyDirection != null &&
                    SkyDirection.Equals(input.SkyDirection)
                ) && 
                (
                    ToCoordsIndex == input.ToCoordsIndex ||
                    ToCoordsIndex != null &&
                    ToCoordsIndex.Equals(input.ToCoordsIndex)
                ) && 
                (
                    TurnDirection == input.TurnDirection ||
                    TurnDirection != null &&
                    TurnDirection.Equals(input.TurnDirection)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Coord != null)
                    hashCode = hashCode * 59 + Coord.GetHashCode();
                if (CumDistance != null)
                    hashCode = hashCode * 59 + CumDistance.GetHashCode();
                if (CumDuration != null)
                    hashCode = hashCode * 59 + CumDuration.GetHashCode();
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                if (DistanceDown != null)
                    hashCode = hashCode * 59 + DistanceDown.GetHashCode();
                if (DistanceUp != null)
                    hashCode = hashCode * 59 + DistanceUp.GetHashCode();
                if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                if (FromCoordsIndex != null)
                    hashCode = hashCode * 59 + FromCoordsIndex.GetHashCode();
                if (Manoeuvre != null)
                    hashCode = hashCode * 59 + Manoeuvre.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (SkyDirection != null)
                    hashCode = hashCode * 59 + SkyDirection.GetHashCode();
                if (ToCoordsIndex != null)
                    hashCode = hashCode * 59 + ToCoordsIndex.GetHashCode();
                if (TurnDirection != null)
                    hashCode = hashCode * 59 + TurnDirection.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
