/* 
 * Trip Planner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 10.6.21.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace TfNSWOpenData.Models
{
    /// <summary>
    /// This element describes a single journey returned by &#x60;trip&#x60;
    /// </summary>
    [DataContract]
        public partial class TripRequestResponseJourney :  IEquatable<TripRequestResponseJourney>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TripRequestResponseJourney" /> class.
        /// </summary>
        /// <param name="isAdditional">XXX.</param>
        /// <param name="legs">This element contains one or more legs that constitute the trip..</param>
        /// <param name="rating">XXX.</param>
        public TripRequestResponseJourney(bool? isAdditional = default, List<TripRequestResponseJourneyLeg> legs = default, int? rating = default)
        {
            IsAdditional = isAdditional;
            Legs = legs;
            Rating = rating;
        }
        
        /// <summary>
        /// XXX
        /// </summary>
        /// <value>XXX</value>
        [DataMember(Name="isAdditional", EmitDefaultValue=false)]
        public bool? IsAdditional { get; set; }

        /// <summary>
        /// This element contains one or more legs that constitute the trip.
        /// </summary>
        /// <value>This element contains one or more legs that constitute the trip.</value>
        [DataMember(Name="legs", EmitDefaultValue=false)]
        public List<TripRequestResponseJourneyLeg> Legs { get; set; }

        /// <summary>
        /// XXX
        /// </summary>
        /// <value>XXX</value>
        [DataMember(Name="rating", EmitDefaultValue=false)]
        public int? Rating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TripRequestResponseJourney {\n");
            sb.Append("  IsAdditional: ").Append(IsAdditional).Append("\n");
            sb.Append("  Legs: ").Append(Legs).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TripRequestResponseJourney);
        }

        /// <summary>
        /// Returns true if TripRequestResponseJourney instances are equal
        /// </summary>
        /// <param name="input">Instance of TripRequestResponseJourney to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TripRequestResponseJourney input)
        {
            if (input == null)
                return false;

            return 
                (
                    IsAdditional == input.IsAdditional ||
                    IsAdditional != null &&
                    IsAdditional.Equals(input.IsAdditional)
                ) && 
                (
                    Legs == input.Legs ||
                    Legs != null &&
                    input.Legs != null &&
                    Legs.SequenceEqual(input.Legs)
                ) && 
                (
                    Rating == input.Rating ||
                    Rating != null &&
                    Rating.Equals(input.Rating)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (IsAdditional != null)
                    hashCode = hashCode * 59 + IsAdditional.GetHashCode();
                if (Legs != null)
                    hashCode = hashCode * 59 + Legs.GetHashCode();
                if (Rating != null)
                    hashCode = hashCode * 59 + Rating.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
